// config
export const UPDATE_CONTENT_LAYOUT = 'UPDATE_CONTENT_LAYOUT'
export const UPDATE_SIDEBAR_STATE = 'UPDATE_SIDEBAR_STATE'
export const UPDATE_APP_STATE = 'UPDATE_APP_STATE'

// toast
export const MAKE_TOAST = 'MAKE_TOAST'

// brand
export const GET_BRAND_LIST = 'GET_BRAND_LIST'
export const UPDATE_BRAND_LIST = 'UPDATE_BRAND_LIST'
export const UPDATE_SELECTED_BRAND = 'UPDATE_SELECTED_BRAND'
export const GET_BRAND_ID_BY_SLUG = 'GET_BRAND_ID_BY_SLUG'
export const UPDATE_BRAND_SLUG_STATE = 'UPDATE_BRAND_SLUG_STATE'

// category
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST'
export const UPDATE_CATEGORY_LIST = 'UPDATE_CATEGORY_LIST'
export const HANDLE_SECONDARY_CATEGORY = 'HANDLE_SECONDARY_CATEGORY'
export const HANDLE_THIRD_CATEGORY = 'HANDLE_THIRD_CATEGORY'

// Handle downloadbox
export const ADD_ITEM_TO_BOX = 'ADD_ITEM_TO_BOX'
export const REMOVE_ITEM_FROM_BOX = 'REMOVE_ITEM_FROM_BOX'
export const SET_DOWNLOAD_BOX = 'SET_DOWNLOAD_BOX'
export const SET_DOWNLOAD_BOX_FROM_CACHE = 'SET_DOWNLOAD_BOX_FROM_CACHE'

// Packages
export const GET_PACKAGE_BY_BRAND = 'GET_PACKAGE_BY_BRAND'
export const UPDATE_PACKAGE = 'UPDATE_PACKAGE'
export const SET_PACKAGE_LOADING = 'SET_PACKAGE_LOADING'

// Files
export const GET_RECENT_FILES = 'GET_RECENT_FILES'
export const SET_RECENT_FILES_LOADING = 'SET_RECENT_FILES_LOADING'
export const UPDATE_RECENT_FILES = 'UPDATE_RECENT_FILES'
export const SEARCH_FILES = 'SEARCH_FILES'
export const UPDATE_SEARCH_FILES = 'UPDATE_SEARCH_FILES'

// Criteria
export const UPDATE_CATEGORY_CRITERIA = 'UPDATE_CATEGORY_CRITERIA'
export const UPDATE_SEARCH_QUERY_CRITERIA = 'UPDATE_SEARCH_QUERY_CRITERIA'

// Suggestions
export const GET_SUGGESTIONS = 'GET_SUGGESTIONS'
export const UPDATE_SUGGESTIONS = 'UPDATE_SUGGESTIONS'
export const UPDATE_VISIBLE_STATE = 'UPDATE_VISIBLE_STATE'
